# Generated by Django 4.2.6 on 2023-12-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productviewhistory',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Product View Histories'},
        ),
        migrations.RenameField(
            model_name='productviewhistory',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
