# Generated by Django 4.2.6 on 2023-12-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_rating_product_total_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='total_rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='user_rating',
        ),
    ]
