# Generated by Django 4.2.6 on 2023-12-20 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_users_wishlist'),
        ('products', '0011_rename_total_rating_product_rating_and_more'),
    ]

    operations = [
    ]
